added command line option to pick numSites

diff --git a/scripts/run_msite_scenarios b/scripts/run_msite_scenarios
--- a/scripts/run_msite_scenarios
+++ b/scripts/run_msite_scenarios
@@ -1,12 +1,48 @@
 #!/bin/bash
-echo "Running Scenario1.1"
-python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario1.1/site1_config.json
-python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario1.1/site2_config.json
-python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario1.1/site3_config.json
 
-echo "Running Scenario1.2"
-python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario1.2/site1_config.json
-python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario1.2/site2_config.json
-python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario1.2/site3_config.json
+function runAllScenarios() {
+    scenario1.1 $1
+    scenario1.2 $1
+    echo "Done"
+}
 
-echo "Done"
+function scenario() {
+    python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario$1/site1_config.json
+    python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario$1/site2_config.json
+    if [ $numSites -eq 3 ]; then
+        python ../applications/multisite/intersite.py --config ~/Code/acitoolkit/configs/scenario$1/site3_config.json
+    fi
+}
+
+function scenario1.1() {
+    echo "Running Scenario1.1"
+    scenario 1.1 numSites
+}
+
+function scenario1.2() {
+    echo "Running Scenario1.2"
+    scenario 1.2 numSites
+}
+
+
+# setup defaults
+numSites=2
+
+if [ $# -gt 0 ]; then
+    while getopts "n:" arg; do
+      case $arg in
+        n)
+            numSites=$OPTARG
+            ;;
+        *)
+            echo "Invalid option specified"
+            echo "Usage: run_msite_scenarions [-n]"
+            echo "      -n: number of sites (default is 2)"
+            exit 1
+            ;;
+      esac
+    done
+    runAllScenarios
+else
+    runAllScenarios
+fi
